config/routes.rb
Rails.application.routes.draw do
	resources :scheduled_messages do
	end

	resources :cases
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oscn_case.rb
class OscnCase
	attr_accessor :original_document, :plaintiff, :defendant, :events, :case_number

	def initialize(val)
		@case_number = val
	end

	def to_json
		{
			:plaintiff => @plaintiff,
			:defendant => @defendant,
			:events => @events
		}.to_json
	end

	def source_url
		"http://www.oscn.net/dockets/GetCaseInformation.aspx?db=tulsa&number=#{@case_number}"
	end

	# Integer#chr not working - this does
	# http://stackoverflow.com/questions/10304754/ruby-1-9-what-is-easiest-inverse-of-string-codepoints-to-a
	def unicode_chr(val)
		[val].inject('') {|s, cp| s << cp }
	end


	def load!
		doc = HTTParty.get(source_url, :timeout => 60).body
		@original_document = doc
		spacea = unicode_chr(32)
		spaceb = unicode_chr(160)
		spaces = "\\s#{spacea}#{spaceb}"
		@plaintiff = $1 if doc =~ />(.*?),<br \/>[#{spaces}]*Plaintiff,/

		@defendant = $1 if doc =~ /v\.<br \/>[#{spaces}]*(.*?),<br \/>[#{spaces}]*Defendant\./

		event_section = $1 if doc =~ /<h2.*?>Events.*?<\/h2>.*?<tbody>(.*?)<\/tbody>/m
		events_html = event_section.split("<tr>")
		events_html.shift # First one is junk
		@events = events_html.map do |evt_html| 
			evt_html = evt_html.split("<td>")
			date_and_evt = evt_html[1]
			date = $1 if date_and_evt =~ /<font.*?>(.*?)<\/font>/m
			event = $1 if date_and_evt =~ /<\/font><br>[#{spaces}]*(.*?)</m
			party = $1 if evt_html[2] =~ /(.*?)</m
			party = party.gsub("&nbsp;", " ")
			docket = $1 if evt_html[3] =~ /[#{spaces}]*(.*?)</m
			{
				:date => (Time.parse(date) rescue "ERR"),
				:event => event,
				:party => party,
				:docket => docket
			}
		end
	end
end

app/models/scheduled_message.rb
class ScheduledMessage < ApplicationRecord
	scope :ready, ->{where("send_at <= CURRENT_TIMESTAMP and sent_at IS NULL")}
	scope :for_source_url, ->(u){where(:source_url => u)}
	scope :send_at_order, ->{order(:send_at)}

	def twilio_client
		@@client ||= Twilio::REST::Client.new(TWILIO_SID, TWILIO_AUTH_TOKEN)
		return @@client
	end

	def self.send_available_messages
		ScheduledMessage.ready.each do |msg|
			msg.send_now!
		end
	end

	def send_now!
		self.twilio_client.account.messages.create({
			:to => destination_phone,
			:from => TWILIO_FROM_PHONE,
			:body => message
		})
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
# encoding: utf-8
class CasesController < ApplicationController
	def index
		redirect_to case_path(params[:case_number]) if params[:case_number].present?
	end

	def show
		@oscn_case = OscnCase.new(params[:id])
		@oscn_case.load!
	end
end

app/controllers/scheduled_messages_controller.rb
class ScheduledMessagesController < ApplicationController
	def massage_phone_number(ph)
		ph = ph.gsub("[^\d\+]+", "")
		if ph[0] != "+"
			if ph[0] == "1"
				ph = "+#{ph}"
			else
				ph = "+1#{ph}"
			end
		end
		return ph
	end

	def create
		msglist = []
		params[:phone_numbers].split(/,\s*/).each do |ph|
			ph = massage_phone_number(ph)
			msg = ScheduledMessage.create!(:source_type => params[:source_type], :source_subtype => params[:source_subtype], :source_url => params[:source_url], :destination_phone => ph, :requestor_ip_address => request.remote_ip, :message => params[:message], :send_at => params[:send_at])
			msglist.push(msg)
		end
		render :json => msglist.to_json
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cases/index.html.erb
<%= form_tag cases_path, :method => :get do %>
	Enter the Case Number:
	<%= text_field_tag "case_number" %>

	<%= submit_tag "Continue" %>
<% end %>

app/views/cases/show.html.erb
<%= form_tag ScheduledMessage.new, :remote => true, :id => "schedule-form" do %>
	<p>
	Case #: <%= @oscn_case.case_number %>
	</p>

	<p>
	Plaintiff: <%= @oscn_case.plaintiff %>
	</p>

	<p>
	Defendant: <%= @oscn_case.defendant %>
	</p>

	<p>
	<label>Phone Numbers (separated by comma)</label>
	<input type="text" name="phone_numbers" id="phone-numbers-field" />
	</p>

	<h3>Times</h3>
	<p>
		<input type="text" name="time1_qty" value="1" /> <select name="time1_type"><option value='hours'>Hours</option><option value="days" selected="selected">Days</option></select><br />
		<input type="text" name="time2_qty" value="2" /> <select name="time2_type"><option value='hours' selected="selected">Hours</option><option value="days">Days</option></select><br />
	</p>
	<%= hidden_field_tag "source_url", @oscn_case.source_url %>
	<%= hidden_field_tag "source_type", "legal" %>
	<%= hidden_field_tag "source_subtype", "oscn" %>
	<%= hidden_field_tag "message", "", :id => "message-field" %>
	<%= hidden_field_tag "send_at", "", :id => "send-at-field" %>

	<script type="text/javascript">
	var oscn_info = <%= raw @oscn_case.to_json %>;
	function scheduled_message_create(idx) {
		if($("#phone-numbers-field").val() == "") {
			alert("Please fill out a phone number");
			return;
		}
		if($("input[name=time1_qty]").val() == "") {
			alert("Please fill out scheduling fields");
			return;
		}
		var evt_info = oscn_info.events[idx];
		var court_date = new Date();
		court_date.setTime(Date.parse(evt_info.date));
		$("#message-field").val("Reminder: " + oscn_info.defendant + " has a court date scheduled on " + court_date.toDateString() + " at " + court_date.toTimeString() + ".  Please arrive promptly.");
		var i = 1;
		var keepgoing = true;
		while(keepgoing) {
			var qty = $("input[name=time" + i + "_qty]").val()	
			if(qty == null) {
				keepgoing = false;
			} else {
				var qtype = $("input[name=time" + i + "_type]").val();
				var offset;
				if(qtype == "days") {
					offset = 1000 * 60 * 60 * 24;
				} else {	
					offset = 1000 * 60 * 60;
				}
				var tmp_date = new Date();
				tmp_date.setTime(court_date.getTime() + offset);
				$("#send-at-field").val(tmp_date.toISOString());
				$.ajax("<%= url_for(ScheduledMessage.new) %>", {
					method: "POST",
					data: $("#schedule-form").serialize(),
					success: function() {
						$("#verify-link").show();
						$("#case-row-" + idx + " .link-cell").html("Scheduled");
					},
					error: function() {
						alert("An error occurred scheduling this message");
					}
				});
			}
			i++;
		}
	}
	</script>

	<table>
	<tr><th>Date</th><th>Event</th><th>Party</th><th>Docket</th></tr>
	<% @oscn_case.events.each_with_index do |evt, idx| %>
		<tr id="case-row-<%= idx %>">
			<td><%= evt[:date] %></td>
			<td><%= evt[:event] %></td>
			<td><%= evt[:party] %></td>
			<td><%= evt[:docket] %></td>
			<td class="link-cell"><a href="#" onclick="scheduled_message_create(<%= idx %>); return false;">Schedule Message</a>
		</tr>
	<% end %>
	</table>

	<p>
		<%= link_to "Verify scheduled messages for this case", scheduled_messages_path(:source_url => @oscn_case.source_url), :id => "verify-link" %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scheduled_messages/index.html.erb
<h3>Scheduled Messages</h3>

Source: <%= params[:source_url] %>

<table>
<tr>
	<th>Destination</th>
	<th>Message</th>
	<th>Time to Send</th>
	<th>Sent At</th>
</tr>
<% ScheduledMessage.send_at_order.for_source_url(params[:source_url]).each do |msg| %>
	<tr>
		<td><%= msg.destination_phone %></td>
		<td><%= msg.message %></td>
		<td><%= msg.send_at %></td>
		<td><%= msg.sent_at %></td>
	</tr>
<% end %>
</table>